This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file M:/docs/manuscripts/swmpr_manu/swmpr_manu.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file swmpr_manu.acn....done (103 entries accepted, 0 rejected).
Sorting entries....done (738 comparisons).
Generating output file swmpr_manu.acr....done (35 lines written, 0 warnings).
Output written in swmpr_manu.acr.
Transcript written in swmpr_manu.alg.
